version: '3.9'
services:
  database:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: skrepr
    ports:
      - '3306'
    volumes:
      - data:/var/lib/mysql
  php:
    build:
      context: ./docker/php
    ports:
      - '9000:9000'
    volumes:
      - ./:/var/www
    depends_on:
      - database
  nginx:
    container_name: nginx
    image: nginx:stable-perl
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database

volumes:
  data:
